#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_chalice="0.0.1"
  jq -n --arg chalice "$ver_chalice" '{chalice: $chalice}'
}

version "$@"
